
language: python

# python version
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'CREATE DATABASE politicalv2test;' -U postgres

# command to run tests
script:
  - coverage run --source=app.api.v2 -m pytest app/api/v2/tests -v -W error::UserWarning && coverage report

# Post coverage results to coverage.io
after_success:
- coveralls
- codeclimate-test-reporter